// This file is autogenerated; changes may be overwritten.

export type ResponseStatus = 'OK' | 'CREATED' | 'INCOMPLETE' | 'REJECTED' | 'NO_RESULTS' | 'MALFORMED';

export class Response {
    constructor(public status: ResponseStatus, public message: string) { }
}

export class DataResponse<T> extends Response {
    constructor(status: ResponseStatus, message: string, public data: T) {
        super(status, message);
    }
}
